#!/bin/sh
. ./common.sh

build_level_i() {
	MAP_PATH="$1"
	CMF_PATH="$2"
	shift
	shift
	if [ -e "$MAP_PATH" ]; then
		echo "building: $MAP_PATH -> $CMF_PATH"
		dotnet run --no-restore -- "$MAP_PATH" "$NARBACULAR/$CMF_PATH" --texdir "$NARBACULAR/video/" "$@"
	else
		echo "$MAP_PATH did not exist and was not built."
	fi
}

build_level() {
	# no longer using --digipen-wad, binary matching seems kinda impossible (?)
	build_level_i "$NARBACULAR/RMF/$1.map" "levels/$1.cmf" --minify
}

if [ "$1" = "" ]; then
	# build original level set (converted to MAP via Hammer 3.4)
	build_level artroom
	build_level BoulderDash
	build_level FireWithFire
	build_level HallwayToHell
	build_level LedgeLadder
	build_level LongHaul
	build_level LongHaul2
	build_level PolishingUp
	build_level VeryVertical
elif [ "$1" = "onetest" ]; then
	build_level_i "$NARBACULAR/expie/onetest.map" expie/onetest_net.cmf
elif [ "$1" = "choptest" ]; then
	build_level_i "choptest.map" levels/ctest.cmf --chop --minify
	build_level_i "choptest.map" levels/ctest_nc.cmf --minify
elif [ "$1" = "twodoor" ]; then
	build_level_i "twodoor.map" levels/twodoor.cmf --chop --minify
elif [ "$1" = "realtest" ]; then
	build_level_i "realtest.map" levels/realtest.cmf --chop --minify
else
	echo "unknown submode $1"
fi
