[book]
authors = ["t20kdc"]
language = "en"
src = "mdbook_generated_src"
title = "'vrc-stuff' notes"

[output.html]
# While this is a really nice feature, we can't have it because we can't specify it on a chapter-by-chapter basis.
sidebar-header-nav = false

[output.html.search.chapter]
# Sadly, we can't allow searching by individual extern; it keeps crashing the browser.
# In addition, mdbook had to be updated from v0.4.35 to v0.5.2 to actually support this.
"ext" = { enable = false }
