#!/usr/bin/env python3

cf = open("/usr/share/doc/picolibc-riscv64-unknown-elf/copyright", "r")

# "Files:" lines make up the majority of the file.
# They don't serve any useful purpose for our purposes and in practice make the text undisplayable.
files_mode = False

while True:
	line = cf.readline()
	if line == "":
		break
	line = line.rstrip()

	# check if we need to terminate files mode
	if files_mode:
		if not line.startswith(" "):
			files_mode = False

	if files_mode:
		pass
	elif line.startswith("Files:"):
		files_mode = True
	else:
		print(line)
