#!/bin/sh -e
# This script is kind of like emcc in spirit, though it is quite limited in execution.
# It adds the kip32 SDK linker script and include directory.
# If you need a full C library, you should probably do things manually and just pull in what you need.

# -- COPY-PASTED HEADER --
WHERE_AM_I="`readlink -f "$0"`"
export KIP32_SDK="`dirname "$WHERE_AM_I"`"
# ------------------------

# this option is used so that science.c can avoid using M-extension instructions during most tests
if [ "$KIP32CC_OVERRIDE_ARCH" != "" ]; then
	KIP32CC_ARCH="$KIP32CC_OVERRIDE_ARCH"
else
	KIP32CC_ARCH="rv32im"
fi

exec riscv64-unknown-elf-gcc -mabi=ilp32 "-march=$KIP32CC_ARCH" -nostartfiles -nolibc -ffreestanding -T "$KIP32_SDK/kip32.ld" -I "$KIP32_SDK/include" "$@"
