#!/bin/sh -e
# This is useful for testing the libc (or for testing code tightly coupled to the libc).

# -- COPY-PASTED HEADER --
WHERE_AM_I="`readlink -f "$0"`"
export KIP32_SDK="`dirname "$WHERE_AM_I"`"
# ------------------------

# this option exists so that science.c can avoid using M-extension instructions during most tests
if [ "$KIP32CC_OVERRIDE_ARCH" != "" ]; then
	KIP32CC_ARCH="$KIP32CC_OVERRIDE_ARCH"
else
	KIP32CC_ARCH="rv32im"
fi

exec riscv64-unknown-elf-gcc -mabi=ilp32 "-march=$KIP32CC_ARCH" -ffreestanding -specs="$KIP32_SDK/libcqemu.specs" "$@"
