#!/bin/sh
dotnet run ../../../../vrc-projects/qroot/projekt/preproom2-compile.bsp /media/ramdisk/dump.obj
dotnet run ../../../kvassets/Assets/mapTest/areaportal-compile.bsp /media/ramdisk/dump_ap.obj
dotnet run ~/.steam/steam/steamapps/common/Half-Life/valve/maps/boot_camp.bsp /media/ramdisk/dump_hl.obj
