use json::JsonValue;
use std::env;
use std::fs;
use std::path::Path;

fn push_rust_str(a: &mut String, b: &str) {
    // this is BAD!!!
    a.push_str("\"");
    a.push_str(b);
    a.push_str("\"");
}

fn main() {
    let api: JsonValue = kudon_apijson::as_json();
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated.rs");

    let mut totality = String::new();

    totality.push_str(r##"
// This file is automatically generated during kudoninfo build

#[allow(non_upper_case_globals)]
#[rustfmt::skip]
/// One static value per known [UdonType].
/// Because of the sheer amount of files that would otherwise be generated, this module's contents are not documented.
pub mod udon_types {
    use std::borrow::Cow;
    use crate::UdonType;
"##);
    for entry in api["types"].entries() {
        totality.push_str("    #[doc(hidden)]\n");
        totality.push_str("    pub static ");
        totality.push_str(entry.0);
        totality.push_str(": UdonType =\n");
        totality.push_str("        UdonType {\n");
        totality.push_str("            name: Cow::Borrowed(");
        push_rust_str(&mut totality, entry.0);
        totality.push_str("),\n");
        totality.push_str("            odin_name: Cow::Borrowed(");
        push_rust_str(&mut totality, entry.1["odin_name"].as_str().unwrap());
        totality.push_str("),\n");
        if entry.1["sync_type"].is_number() {
            totality.push_str("            sync_type: Some(");
            totality.push_str(&format!("{}", entry.1["sync_type"].as_i32().unwrap()));
            totality.push_str("),\n");
        } else {
            totality.push_str("            sync_type: None,\n");
        }
        totality.push_str("        };\n");
    }
    totality.push_str(
        r##"
}

/// All known [UdonType]s.
/// **This list is guaranteed to be sorted.**
pub static UDON_TYPES: &[&'static UdonType] = &[
"##,
    );
    let mut type_keys: Vec<String> = api["types"].entries().map(|v| v.0.to_string()).collect();
    type_keys.sort();

    for type_key in type_keys {
        totality.push_str("    &udon_types::");
        totality.push_str(&type_key);
        totality.push_str(",\n");
    }
    totality.push_str(
        r##"
];

/// Mapping of synctype numbers to corresponding [UdonType]s.
pub static UDON_SYNCTYPES: &[Option<&'static UdonType>] = &[
"##,
    );

    for st in api["sync_types"].members() {
        if st.is_object() {
            totality.push_str("    Some(&udon_types::");
            totality.push_str(st["name"].as_str().unwrap());
            totality.push_str("),\n");
        } else {
            totality.push_str("    None,\n");
        }
    }
    totality.push_str("];\n");

    fs::write(&dest_path, totality).unwrap();
    println!("cargo::rerun-if-changed=build.rs");
}
