#!/usr/bin/env python3
import json

dfile = open("datamine.txt", "r")

data = {}
data_externs = {}
data_types = {}
data_events = {}
data_synctype = []
data["externs"] = data_externs
data["types"] = data_types
data["events"] = data_events
data["sync_types"] = data_synctype

while True:
	decltype = dfile.readline().strip()
	if decltype == "END":
		break
	elif decltype == "EXTERN":
		extern_id = dfile.readline().strip()
		extern_type = dfile.readline().strip()
		extern_id_type = extern_id[:extern_id.find(".")]
		extern_id_signature = extern_id[extern_id.find(".") + 1:]
		extern_parameters = []
		for _ in range(int(dfile.readline().strip())):
			p_name = dfile.readline().strip()
			p_type = dfile.readline().strip()
			p_dir = dfile.readline().strip()
			extern_parameters.append({
				"name": p_name,
				"type": p_type,
				"dir": p_dir,
			})
		data_externs[extern_id] = {
			"id": extern_id,
			"id_type": extern_id_type,
			"id_signature": extern_id_signature,
			"type": extern_type,
			"parameters": extern_parameters
		}
		if not (extern_id_type in data_types):
			# fake replacable static type
			data_types[extern_id_type] = {
				"static": True,
				"name": extern_id_type,
				"odin_name": "",
				"base": "",
				"interfaces": [],
				"sync_type": None
			}
	elif decltype == "EVENT":
		event_name = dfile.readline().strip()
		event_entrypoint = dfile.readline().strip()
		event_parameters = []
		for _ in range(int(dfile.readline().strip())):
			p_name = dfile.readline().strip()
			p_type = dfile.readline().strip()
			event_parameters.append({
				"name": p_name,
				"type": p_type
			})
		data_events[event_entrypoint] = {
			"name": event_name,
			"entrypoint": event_entrypoint,
			"parameters": event_parameters
		}
	elif decltype == "TYPE":
		type_name = dfile.readline().strip()
		type_odin_name = dfile.readline().strip()
		type_base = dfile.readline().strip()
		type_interfaces = []
		for _ in range(int(dfile.readline().strip())):
			type_interfaces.append(dfile.readline().strip())
		data_types[type_name] = {
			"static": False,
			"name": type_name,
			"odin_name": type_odin_name,
			"base": type_base,
			"interfaces": type_interfaces,
			"sync_type": None
		}
		if type_base == "SystemEnum":
			data_types[type_name]["enumValues"] = {}
	elif decltype == "EVAL":
		eval_type = dfile.readline().strip()
		eval_name = dfile.readline().strip()
		eval_value = int(dfile.readline().strip())
		data_types[eval_type]["enumValues"][eval_name] = eval_value
	elif decltype == "SYNCTYPEID":
		st_id = int(dfile.readline().strip())
		st_ty = dfile.readline().strip()
		while len(data_synctype) <= st_id:
			data_synctype.append(None)
		data_synctype[st_id] = {
			"sync_type": st_id,
			"name": st_ty
		}
		data_types[st_ty]["sync_type"] = st_id
	else:
		raise Exception("Unknown decltype " + decltype)

# --

json.dump(data, open("api.json", "w"), indent="\t")

# --

sync_type_table = open("synctypes.md", "w")
sync_type_table.write("| Type Index | Udon Type |\n")
sync_type_table.write("| ---------- | --------- |\n")
for st in data_synctype:
	if st != None:
		sync_type_table.write("| " + str(st["sync_type"]) + " | `" + st["name"] + "` |\n")
sync_type_table.close()

# --

generated_rs = open("../../kip32/kudoninfo/src/generated.rs", "w")

generated_rs.write("""//! This file is automatically generated using datamine2json.py

use crate::UdonType;

#[allow(non_upper_case_globals)]
#[rustfmt::skip]
/// One static value per known [UdonType].
/// Because of the sheer amount of files that would otherwise be generated, this module's contents are not documented.
pub mod udon_types {
    use std::borrow::Cow;
    use crate::UdonType;
""");

# -- BE EXTREMELY CAREFUL WHEN MAKING CHANGES IN THIS AREA! THE GIT DIFFS WILL BE MASSIVE! --
for ut_key in sorted(list(data_types.keys())):
	dt = data_types[ut_key]
	generated_rs.write("    #[doc(hidden)]\n")
	generated_rs.write("    pub static " + ut_key + ": UdonType =\n")
	generated_rs.write("        UdonType {\n")
	generated_rs.write("            name: Cow::Borrowed(\"" + ut_key + "\"),\n")
	generated_rs.write("            odin_name: Cow::Borrowed(\"" + dt["odin_name"] + "\"),\n")
	if dt["sync_type"] == None:
		generated_rs.write("            sync_type: None,\n")
	else:
		generated_rs.write("            sync_type: Some(" + str(dt["sync_type"]) + "),\n")
	generated_rs.write("        };\n")

generated_rs.write("}\n\n")

generated_rs.write("/// All known [UdonType]s.\n")
generated_rs.write("/// **This list is guaranteed to be sorted.**\n")
generated_rs.write("pub static UDON_TYPES: &[&'static UdonType] = &[\n")
for ut_key in sorted(list(data_types.keys())):
	generated_rs.write("    &udon_types::" + ut_key + ",\n")
generated_rs.write("];\n\n")

generated_rs.write("/// Mapping of synctype numbers to corresponding [UdonType]s.\n")
generated_rs.write("pub static UDON_SYNCTYPES: &[Option<&'static UdonType>] = &[\n")
for st in data_synctype:
	if st != None:
		generated_rs.write("    Some(&udon_types::" + st["name"] + "),\n")
	else:
		generated_rs.write("    None,\n")
generated_rs.write("];\n")

generated_rs.close()
